// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEmcartago.Server.Data;

#nullable disable

namespace ProyectoEmcartago.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220808212852_PEDSYP")]
    partial class PEDSYP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Formato_De_Permisos.FormatoPermisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autoriza_Jefe_Inmediato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autoriza_SubGerentes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Causa_Del_Permiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Causa_Del_Permiso_Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Desde")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Formato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Hasta")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oficina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("formatoPermisos");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Ingreso_y_Salida.IngresoySalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autorizado_por")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo_bien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("De_su_propiedad")
                        .HasColumnType("bit");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Despacho")
                        .HasColumnType("bit");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Devolucion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_entrada")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_salida")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Jefe_que_Autoriza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mantenimiento_y_o_Reparacion")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Persona_que_se_Autoriza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prestamo")
                        .HasColumnType("bit");

                    b.Property<bool>("Realizar_trabajo")
                        .HasColumnType("bit");

                    b.Property<string>("Solicitado_por")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tranferencia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fecha_Autorizado_por")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_Solicitado_por")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("hora_Autorizado_por")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("hora_Solicitado_por")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("IngresoySalidaEquiposComputo");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_PEDSYP.PEDSYP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ajustes_bornes_bateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ajustes_bornes_bateria_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Altas_y_bajas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Altas_y_bajas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bomba_hidráulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bomba_hidráulica_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindro_de_extension_del_brazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindro_de_extension_del_brazo_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindros_de_levante_del_brazo_del_boom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindros_de_levante_del_brazo_del_boom_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindros_de_movimientos_laterales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindros_de_movimientos_laterales_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinturon_Seguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinturon_Seguridad_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccionales_delanteras_p")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccionales_delanteras_p_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccionales_traseras_p")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccionales_traseras_p_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drenar_tanques_aire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drenar_tanques_aire_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drenarfiltro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drenarfiltro_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGCCCSFLPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGCCCSFLPI_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Espejos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Espejos_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estad_presencia_de_tapa_sin_goteo_fugas_TC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estad_presencia_de_tapa_sin_goteo_fugas_TC_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estad_presencia_de_tapa_sin_goteo_fugas_TU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estad_presencia_de_tapa_sin_goteo_fugas_TU_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Manguera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Manguera_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Verificar_cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Verificar_cantidad_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_abullamientos_cortes_desgastes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_abullamientos_cortes_desgastes_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_ajuste_tapa_filtros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_ajuste_tapa_filtros_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_de_freno_de_ahogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_de_freno_de_ahogo_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_de_frenos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_de_frenos_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_y_tensión_de_correas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_y_tensión_de_correas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estroboscopicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estroboscopicas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Revision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funcionamiento_alarma_y_camara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcionamiento_alarma_y_camara_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcionamiento_pito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcionamiento_pito_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit");

                    b.Property<string>("Luces_reversa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luces_reversa_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mangueras_tubos_conexiones_racores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mangueras_tubos_conexiones_racores_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manijas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manijas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_caja_velocidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_caja_velocidades_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_direccion_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_motor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_motor_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_ruedas_delanteras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_ruedas_delanteras_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_transmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_aceite_de_transmision_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_de_limpiabrisas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_de_limpiabrisas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_de_refrigerante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_de_refrigerante_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parabrisas_Ventanas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parabrisas_Ventanas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa_Vehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precion_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puertas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puertas_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revise_el_sistema_del_secador_de_aire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revise_el_sistema_del_secador_de_aire_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revision_verificar_de_tamiz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revision_verificar_de_tamiz_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revisión_practica_frenos_transmision_y_embrague")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revisión_practica_frenos_transmision_y_embrague_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruido_motor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruido_motor_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Silla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Silla_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sin_fugas_de_fluidos_por_mangueras_accesorios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sin_fugas_de_fluidos_por_mangueras_accesorios_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sist_Comunicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sist_Comunicacion_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soat_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stop_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tablero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tablero_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tapas_bateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tapas_bateria_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarjeta_de_propiedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarjeta_de_propiedad_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecno_mecanica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecno_mecanica_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracera_de_trabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracera_de_trabajo_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vencimiento_S")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vencimiento_TM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vencimiento_TP")
                        .HasColumnType("datetime2");

                    b.Property<string>("Verificacion_de_nivel_aceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verificacion_de_nivel_aceite_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verificar_nivel_conexion_electrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verificar_nivel_conexion_electrica_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("licencia_de_conduccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("licencia_de_conduccion_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PEDSYP");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.Imagen_UsoEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InspeccionUsoEppId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionUsoEppId");

                    b.ToTable("Imagenes_UsoEpp");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Actividad_Mayor_O_Igual_A_15_Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Caucho_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Seguridad_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Seguridad_Sin_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camisa_Con_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Careta_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carnet_De_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Casco_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chaleco_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dotacion_Contratista_Con_Reflectivo_Marcada_Como_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epps_De_Acuerdo_A_La_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gafas_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gafas_De_Seguridad_lente_Oscuro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_Carnaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_De_Caucho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_Tipo_Ingeniero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Impermeable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Mascarilla_Con_Filtros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Coordinador_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Actividad_Mayor_O_Igual_A_15_Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Caucho_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Seguridad_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Seguridad_Sin_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Camisa_Con_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Careta_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Carnet_De_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Casco_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Chaleco_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Dotacion_Contratista_Con_Reflectivo_Marcada_Como_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Epps_De_Acuerdo_A_La_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gafas_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gafas_De_Seguridad_lente_Oscuro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gorra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_Carnaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_De_Caucho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_Tipo_Ingeniero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Impermeable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Mascarilla_Con_Filtros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Pantalon_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Protector_Auditivo_De_Copa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Protector_Auditivo_Insercion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Seguridad_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Sitio_Coordinador_Para_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Tapa_Bocas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opcion_Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otro_Elemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pantalon_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protector_Auditivo_De_Copa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protector_Auditivo_Insercion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable_Inspeccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seguridad_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sitio_Coordinador_Para_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tapa_Bocas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("inspeccionUsoEpp");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.Imagen_UsoEpp", b =>
                {
                    b.HasOne("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", null)
                        .WithMany("Imagenes_UsoEpp")
                        .HasForeignKey("InspeccionUsoEppId");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", b =>
                {
                    b.Navigation("Imagenes_UsoEpp");
                });
#pragma warning restore 612, 618
        }
    }
}
