// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEmcartago.Server.Data;

#nullable disable

namespace ProyectoEmcartago.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220803193349_IngresoySalida")]
    partial class IngresoySalida
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Formato_De_Permisos.FormatoPermisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autoriza_Jefe_Inmediato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autoriza_SubGerentes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Causa_Del_Permiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Causa_Del_Permiso_Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Desde")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Formato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Hasta")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oficina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("formatoPermisos");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Ingreso_y_Salida.IngresoySalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autorizado_por")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo_bien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("De_su_propiedad")
                        .HasColumnType("bit");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Despacho")
                        .HasColumnType("bit");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Devolucion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_entrada")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_salida")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Jefe_que_Autoriza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mantenimiento_y_o_Reparacion")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Persona_que_se_Autoriza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prestamo")
                        .HasColumnType("bit");

                    b.Property<bool>("Realizar_trabajo")
                        .HasColumnType("bit");

                    b.Property<string>("Solicitado_por")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tranferencia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fecha_Autorizado_por")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_Solicitado_por")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("hora_Autorizado_por")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("hora_Solicitado_por")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("IngresoySalidaEquiposComputo");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.Imagen_UsoEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InspeccionUsoEppId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionUsoEppId");

                    b.ToTable("Imagenes_UsoEpp");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Actividad_Mayor_O_Igual_A_15_Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Caucho_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Seguridad_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Botas_De_Seguridad_Sin_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camisa_Con_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Careta_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carnet_De_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Casco_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chaleco_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dotacion_Contratista_Con_Reflectivo_Marcada_Como_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epps_De_Acuerdo_A_La_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gafas_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gafas_De_Seguridad_lente_Oscuro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_Carnaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_De_Caucho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes_Tipo_Ingeniero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Impermeable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Mascarilla_Con_Filtros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Coordinador_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Actividad_Mayor_O_Igual_A_15_Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Caucho_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Seguridad_Con_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Botas_De_Seguridad_Sin_Puntera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Camisa_Con_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Careta_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Carnet_De_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Casco_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Chaleco_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Dotacion_Contratista_Con_Reflectivo_Marcada_Como_Contratista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Epps_De_Acuerdo_A_La_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gafas_De_Seguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gafas_De_Seguridad_lente_Oscuro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Gorra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_Carnaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_De_Caucho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Guantes_Tipo_Ingeniero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Impermeable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Mascarilla_Con_Filtros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Pantalon_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Protector_Auditivo_De_Copa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Protector_Auditivo_Insercion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Seguridad_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Sitio_Coordinador_Para_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Tapa_Bocas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opcion_Disposicion_De_Los_Epps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otro_Elemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pantalon_Reflectivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protector_Auditivo_De_Copa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protector_Auditivo_Insercion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable_Inspeccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seguridad_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sitio_Coordinador_Para_Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tapa_Bocas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trabajo_En_Alturas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("inspeccionUsoEpp");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.Imagen_UsoEpp", b =>
                {
                    b.HasOne("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", null)
                        .WithMany("Imagenes_UsoEpp")
                        .HasForeignKey("InspeccionUsoEppId");
                });

            modelBuilder.Entity("ProyectoEmcartago.Shared.Entidades.Entidad_Uso_Epp.InspeccionUsoEpp", b =>
                {
                    b.Navigation("Imagenes_UsoEpp");
                });
#pragma warning restore 612, 618
        }
    }
}
